apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-openshift-builds/shipwright-io?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "main" &&
      (
        files.all.exists(x, x.matches('build/cmd/git/|build/pkg/git/|.konflux/git-cloner/')) ||
        files.all.exists(x, x.matches('build/go.mod|build/go.sum')) ||
        files.all.exists(x, x.matches('.tekton/openshift-builds-git-cloner-pull-request.yaml'))
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: openshift-builds
    appstudio.openshift.io/component: openshift-builds-git-cloner
    pipelines.appstudio.openshift.io/type: build
  name: openshift-builds-git-cloner-on-pull-request
  namespace: rh-openshift-builds-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds-git-cloner:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: .konflux/git-cloner/Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-dev-package-managers
    value: "true"
  - name: build-platforms
    value:
      - linux/x86_64
  - name: prefetch-input
    value: '{"packages": [{"type": "gomod", "path": "build"},{"type": "rpm","path": ".konflux/git-cloner"}]}'
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/redhat-openshift-builds/release.git
      - name: revision
        value: main
      - name: pathInRepo
        value: /pipelines/konflux-build-multi-platform.yaml
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
