apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-openshift-builds/shipwright-io?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" &&
      target_branch == "builds-1.5" &&
      (
        files.all.exists(x, x.matches('build/version/|build/pkg/webhook/|build/pkg/ctxlog/|build/cmd/shipwright-build-webhook/|.konflux/webhook/')) ||
        files.all.exists(x, x.matches('build/go.mod|build/go.sum')) ||
        files.all.exists(x, x.matches('.tekton/openshift-builds-webhook-push.yaml'))
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: openshift-builds-1-5
    appstudio.openshift.io/component: openshift-builds-webhook-1-5
    pipelines.appstudio.openshift.io/type: build
  name: openshift-builds-webhook-1-5-on-push
  namespace: rh-openshift-builds-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds-webhook-1-5:{{revision}}
  - name: dockerfile
    value: .konflux/webhook/Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: prefetch-input
    value: '{"packages": [{"type": "gomod", "path": "build"}]}'
  pipelineRef:
    params:
    - name: url
      value: https://github.com/redhat-openshift-builds/release.git
    - name: revision
      value: main
    - name: pathInRepo
      value: /pipelines/konflux-build-multi-platform.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-openshift-builds-webhook-1-5
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
