apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-openshift-builds/shipwright-io?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" &&
      target_branch == "main" &&
      (
        files.all.exists(x, x.matches('rpms.lock.yaml')) ||
        files.all.exists(x, x.matches('.tekton/openshift-builds-git-cloner-push.yaml|.konflux/git-cloner')) ||
        event_title.startsWith("Update build digest")
      )
  labels:
    appstudio.openshift.io/application: openshift-builds
    appstudio.openshift.io/component: openshift-builds-git-cloner
    pipelines.appstudio.openshift.io/type: build
  name: openshift-builds-git-cloner-on-push
  namespace: rh-openshift-builds-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds-git-cloner:{{revision}}
  - name: dockerfile
    value: .konflux/git-cloner/Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: prefetch-dev-package-managers
    value: "true"
  - name: build-platforms
    value:
    - linux/x86_64
    - linux/arm64
    - linux/ppc64le
    - linux/s390x
  - name: prefetch-input
    value: '{"packages": [{"type": "gomod", "path": "build"},{"type": "rpm"}]}'
  pipelineRef:
    params:
    - name: url
      value: https://github.com/redhat-openshift-builds/release.git
    - name: revision
      value: main
    - name: pathInRepo
      value: /pipelines/konflux-build-multi-platform.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-openshift-builds-git-cloner
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
