apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-openshift-builds/shipwright-io?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "main" &&
      (
        files.all.exists(x, x.matches('build/cmd/git/|build/pkg/git/|.konflux/git-cloner/')) ||
        files.all.exists(x, x.matches('build/go.mod|build/go.sum')) ||
        files.all.exists(x, x.matches('.tekton/openshift-builds-git-cloner-pull-request-test.yaml'))
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: openshift-builds
    appstudio.openshift.io/component: openshift-builds-git-cloner
    pipelines.appstudio.openshift.io/type: build
  name: openshift-builds-git-cloner-on-pull-request
  namespace: rh-openshift-builds-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds-git-cloner:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: .konflux/git-cloner/Dockerfile
  - name: build-source-image
    value: "true"
  - name: hermetic
    value: "true"
  - name: build-platforms
    value:
      - linux/x86_64
#      - linux/arm64
#      - linux/ppc64le
#      - linux/s390x
  - name: prefetch-dev-package-managers
    value: "true"
  - name: prefetch-input
    value: '{"packages": [{"type": "gomod","path": "build"},{"type": "rpm","path": ".konflux/git-cloner"}]}'
  pipelineRef:
    resolver: bundles
    params:
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta@sha256:474b191d925e6066ffbc92929276d33458e27fa4ad04a1ac3eda0b2745e05bb3
      - name: name
        value: docker-build-multi-platform-oci-ta
      - name: kind
        value: pipeline
  taskRunTemplate: {}
#  workspaces:
#    - name: git-auth
#      secret:
#        secretName: '{{ git_auth_secret }}'
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
status: {}